version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./client/.env
    depends_on:
      - web
  web:
    build:
      context: ./jabme
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 -c gunicorn.conf.py --enable-stdio-inheritance --log-level=info
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - mailer
    restart: always
  mailer:
    build:
      context: ./mailer
      dockerfile: Dockerfile
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jabme
      - POSTGRES_PASSWORD=jabme
      - POSTGRES_DB=jabme_prod
  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx:/etc/nginx/conf.d
      # - /etc/letsencrypt/live/covaccinate.tech:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - client
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
