export default {
  RABBITMQ_CONNECTION: "CLOUDAMQP CONNECTION STRING",

  API_KEY1: "YOUR MAILGUN API KEY",
  DOMAIN1: "YOUR MAILGUN DOMAIN",

  API_KEY2: "YOUR MAILGUN API KEY",
  DOMAIN2: "YOUR MAILGUN DOMAIN",

  API_KEY3: "YOUR MAILGUN API KEY",
  DOMAIN3: "YOUR MAILGUN DOMAIN",

  SECRET_HEADER_KEY: "YOUR SECRET HEADER",
  SECRET_HEADER_VALUE: "YOUR SECRET HEADER KEY",
};
