# Generated by Django 3.2.1 on 2021-05-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="count",
        ),
    ]
