# Generated by Django 3.2.1 on 2021-05-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mobile",
        ),
    ]
