# Generated by Django 3.2.2 on 2021-05-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_category",
            field=models.CharField(
                choices=[("18-44", "18-44"), ("45+", "45+")],
                default="18-44",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="district_id",
            field=models.CharField(default=512, max_length=5),
            preserve_default=False,
        ),
    ]
