# Generated by Django 3.2.2 on 2021-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210507_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.CharField(default="satara", max_length=150),
            preserve_default=False,
        ),
    ]
