# Generated by Django 3.2.2 on 2021-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
