# Generated by Django 3.2.2 on 2021-06-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_send_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
