# Generated by Django 3.2.2 on 2021-07-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_email_send_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                ("district", models.CharField(max_length=150)),
                (
                    "district_id",
                    models.CharField(
                        editable=False,
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_send_time",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="district_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_send_time",
        ),
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.district",
            ),
        ),
    ]
