# Generated by Django 3.2.5 on 2021-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="district_id",
            field=models.CharField(
                max_length=5, primary_key=True, serialize=False
            ),
        ),
    ]
